services:

  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
