name: Docker CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-devcontainer:
    name: Build devcontainer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build -f .devcontainer/Dockerfile .

  build-runtime:
    name: Build runtime
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build -f Dockerfile .