name: Docker CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-devcontainer:
    name: Build Devcontainer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build devcontainer
      run: docker build -f .devcontainer/Dockerfile .

  build-runtime:
    name: Build Runtime
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build runtime
      run: docker build -f Dockerfile .