name: Runtime CI

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/runtime.yml
      - src/**
      - Dockerfile
      - compose.yml

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build -f Dockerfile .